### ISSUE TITLE
Database sync with PostgreSQL's native replication mechanism

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#116]
**Acceptance criteria**
- PostgreSQL on heroku/local can be connected
- Some hard-coded configuration is okay at this point
- Know what should be done to get it working e.g we need to specify a port, need to configure PostgreSQL, need additional cloud instances, etc.
- databases can sync with each other.
- Have commands or script to control syncing.
- Tests are written and successful.

**Definition of Done**
I know this is done when I know how to integrate/configure PostgreSQL on heroku/local and also can run synchronization between heroku and local. And the required scripts are in master branch. Alternatively, if symmetric works, we can consider this done and closed since we will not need it.

**Comment by iamvibhorsingh** [comment]
## Setting up

Open terminal and then type `psql.` Go to the database you want to copy from. Make sure you (current user) has replication priviliges. Check using `\dg` . 

## Creating Publication

To create a [publication](https://www.postgresql.org/docs/10/logical-replication-publication.html), use command `CREATE PUBLICATION <name of new publication>;`

This publication needs to be associated with tables you want to replicate.  To associate it with all tables in the database, use `CREATE PUBLICATION <name of new publication> FOR ALL TABLES;` instead of the previous command. 

To add specific tables, use `ALTER PUBLICATION <publication name> ADD TABLE <table1, table2, ... >;` instead. 

## Creating Subscription

Go to the database you want to copy to.

To create a [subscription](https://www.postgresql.org/docs/10/logical-replication-subscription.html), use command `CREATE SUBSCRIPTION < subscription name> CONNECTION <dbname, host, user>PUBLICATION <publication name>;`

# Note: If you want to synchronize 2 local databases, you will need to create a [replication slot](https://www.postgresql.org/docs/9.4/logicaldecoding-explanation.html#AEN67208). 
To do this, use the command `SELECT pg_create_logical_replication_slot('<slot name>', 'pgoutput');`

After this, follow the above instructions of creating a publication. When creating a subscription, use `CREATE SUBSCRIPTION < subscription name> CONNECTION <dbname, host, user>PUBLICATION <publication name> WITH (slot_name=<slot name>, create_slot=false);`
# 
## Important: One major drawback of using inbuilt logical replication (as of postgres 12) is that it only copies data between databases and not the schema nor the tables themselves as mentioned in [the documentation](https://www.postgresql.org/docs/12/logical-replication-subscription.html).  

**Due to this we won't be moving forward with this synchronization method as of now and instead focus all our efforts towards SymmetricDS which doesn't have this drawback.**
