### ISSUE TITLE
Resolve duplicate primary key issue using django with symmetricDS

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-class#181]
**Reproduce step**
1. `python manage.py runserver`
2. Go admin and login
3. Choose an arbitrary model e.g `TemperatureSensor` and add a row
4. Check if it's added successfully
5. Connect to postgres directly (e.g `psql mercury`)
6. `insert into mercury_temperaturesensor (id, created_at, temperature) values (2, '2020-03-27 13:18:11-04', 2);`
7. Do step 2, 3 again

**Expected Behavior**
django model can insert a row into database without an error

**Current Behavior**
duplicate key error
```
duplicate key value violates unique constraint "mercury_temperaturesensor_pkey"
DETAIL:  Key (id)=(2) already exists.
```

**Comment by iamvibhorsingh** [comment]
The bug was due to database and django model data being out of sync. Django has a built-in management command to handle this called [sqlsequencereset](https://docs.djangoproject.com/en/dev/ref/django-admin/#sqlsequencereset). 

So, to remove this error, simply run the command `python manage.py sqlsequencereset` which will generate the SQL commands to run to reset the sequences. To execute it right away automatically, you can pipe the command above `python manage.py sqlsequencereset | python manage.py dbshell`

We are planning to have this command run automatically as part of a script when symmetricds syncs data and will work on it in a future sprint

**Comment by alldne** [comment]
https://stackoverflow.com/questions/43663588/executing-djangos-sqlsequencereset-code-from-within-python
